apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xskc2zbkp-python
  janus-idp.io/tekton: xskc2zbkp-python
  backstage.io/kubernetes-id: xskc2zbkp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xskc2zbkp-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
