apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xskc2zbkp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xskc2zbkp-python 
  name: xskc2zbkp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xskc2zbkp-python 
